# Laboratorium 5
#### Aleksandra Burczyk
#### Monika Gmaj
#### Kinga Jankowska
#### Kamil Łangowski

In [1]:
import pakiet 

In [2]:
help(pakiet)

Help on package pakiet:

NAME
    pakiet

DESCRIPTION
    Ten pakiet zawiera moduły służące do transponowania oraz mnożenia macierzy i sumowania elementów wektora
    @authors: AB, MG, KJ, KŁ

PACKAGE CONTENTS
    mnozenie
    suma
    transpozycja

FILE
    c:\users\studentwftims.lab\downloads\program5\pakiet\__init__.py




In [3]:
import pakiet.mnozenie

Ładuję moduł o nazwie: pakiet.mnozenie


In [4]:
help(pakiet.mnozenie)

Help on module pakiet.mnozenie in pakiet:

NAME
    pakiet.mnozenie - mnoży macierze

FUNCTIONS
    multiplication(A, B)
        Funkcja mnożąca macierze 
        parametry:
            A: numpy array object 
                pierwsza macierz w mnożeniu 
            B: numpy array object 
                druga macierz w mnożeniu

FILE
    c:\users\studentwftims.lab\downloads\program5\pakiet\mnozenie.py




In [5]:
import pakiet.suma

Ładuję moduł o nazwie: pakiet.suma


In [6]:
help(pakiet.suma)

Help on module pakiet.suma in pakiet:

NAME
    pakiet.suma - sumuje elementy wektora

FUNCTIONS
    summation(A)
        Funkcja sumująca elementy tablicy pionowej
        parametry: 
            A: numpy array object 
                sumowany wektor

FILE
    c:\users\studentwftims.lab\downloads\program5\pakiet\suma.py




In [7]:
import pakiet.transpozycja

Ładuję moduł o nazwie: pakiet.transpozycja


In [8]:
help(pakiet.transpozycja)

Help on module pakiet.transpozycja in pakiet:

NAME
    pakiet.transpozycja - transponuje macierze

FUNCTIONS
    transpose(A)
        Funkcja transponująca macierz
        parametry: 
            A: numpy array object 
                macierz, którą transponujemy

FILE
    c:\users\studentwftims.lab\downloads\program5\pakiet\transpozycja.py




In [9]:
import numpy as np
from numpy.linalg import inv

Tablice zmiennych i wag

In [10]:
wydajnosc = np.array([[3],
                      [9],
                      [7],
                      [9.5],
                      [14],
                      [14],
                      [14],
                      [22]])

In [11]:
dlugosc_szkolenia = np.array([[0.5],
                              [1],
                              [1.5],
                              [2],
                              [2.5],
                              [3.5],
                              [4],
                             [4.5]])

In [12]:
liczba_pracownikow = np.array([[4],
                               [4],
                               [4],
                               [16],
                               [4],
                               [4],
                               [1],
                               [4]])

Definiowanie funkcji ważonej metody najmniejszych kwadratów

In [13]:
def WLSM_parameters(x, y, w, b0):
    '''
    Function for parameters calculation of linear regression using weighted least squares method
    x, y, w - numpy array objects
    b0 - boolean TO DO: 1 JEZELI MA BYC B0; 0 JEZELI NIE MA BYC B0
    '''  
    if (b0 == 1):
        # define experiment matrix
        X = np.ones((np.shape(x)[0], np.shape(x)[1] + 1))

        for i in range(0, np.shape(X)[0]):
            for j in range(1, np.shape(X)[1]):
                X[i][j] = x[i][j-1]
                
        print('Experiment matrix: \n'  + str(X))
        
        W = np.diag(w.reshape(1,len(w))[0])
        
        Xt = pakiet.transpozycja.transpose(X)
        print('Transposition of X:\n' +str (Xt))

        XtW = pakiet.mnozenie.multiplication(Xt, W)
        print('Multiplication of X transposed and W :\n' + str(XtW))
        
        XtWX = pakiet.mnozenie.multiplication(XtW, X)
        print('Multiplication of X^tW and X :\n' + str(XtWX))
        
        
        XtWX_inverse = inv(XtWX)
        print('Inversion of X^t * W * X  :\n' + str(XtWX_inverse))

        XtWy = pakiet.mnozenie.multiplication(XtW, y)
        print('Multiplication of X^tW and y:\n' + str(XtWy))

        result = pakiet.mnozenie.multiplication(XtWX_inverse, XtWy)
        print('Parameters:\n' + str(result))
        return(result)
    
    elif (b0 == 0): 
            sum_wxy = pakiet.suma.summation(x * y * w)
            sum_wx2 = pakiet.suma.summation(w * x**2)
            return(sum_wxy/sum_wx2)
    else:
        print('Inproper b0 value. b0 = 0 or b0 = 1.')

In [14]:
WLSM_parameters(x=dlugosc_szkolenia, y=wydajnosc, w=liczba_pracownikow, b0 = 1)

Experiment matrix: 
[[1.  0.5]
 [1.  1. ]
 [1.  1.5]
 [1.  2. ]
 [1.  2.5]
 [1.  3.5]
 [1.  4. ]
 [1.  4.5]]
Transposition of X:
[[1.  1.  1.  1.  1.  1.  1.  1. ]
 [0.5 1.  1.5 2.  2.5 3.5 4.  4.5]]
Multiplication of X transposed and W :
[[ 4.  4.  4. 16.  4.  4.  1.  4.]
 [ 2.  4.  6. 32. 10. 14.  4. 18.]]
Multiplication of X^tW transposed and X :
[[ 41.  90.]
 [ 90. 249.]]
Inversion of X^t * W * X  :
[[ 0.11806543 -0.04267425]
 [-0.04267425  0.01944049]]
Multiplication of X^tW and y:
[[ 442.]
 [1176.]]
Parameters:
[[2.]
 [4.]]


array([[2.],
       [4.]])

(a) $y = 4x +2$

In [15]:
WLSM_parameters(x=dlugosc_szkolenia, y=wydajnosc, w=liczba_pracownikow, b0 = 0)

array([4.72289157])

(b) $y \approx 4.72289157 x$