# Laboratorium 4
#### Aleksandra Burczyk
#### Monika Gmaj
#### Kinga Jankowska
#### Kamil Łangowski

In [1]:
import pandas as pd, numpy as np
from numpy.linalg import inv

Definiujemy funkcję transpozycji macierzy

In [2]:
def transpose(A):
    '''
    Function for matrix transposition
    A - numpy array object
    '''
    B = np.zeros(shape=(np.shape(A)[1], np.shape(A)[0]))
    
    for j in range(np.shape(A)[1]):
        for i in range(np.shape(A)[0]):
            B[j][i] = A[i][j] 
    return B

Definiujemy funkcję mnożenia macierzy

In [3]:
def multiplication(A, B):
    '''
    Function for matrix multiplication
    A, B - numpy array objects
    '''
    C = np.zeros((np.shape(A)[0], np.shape(B)[1]))

    for i in range(np.shape(A)[0]):
        
         for j in range(np.shape(B)[1]):
                
            for k in range(np.shape(B)[0]):
                
                C[i][j] += A[i][k] * B[k][j]
    return C

Definiujemy funkcję wyznaczania parametrów regresji metodą najmniejszych kwadratów

In [7]:
def LSM_parameters(x, y):
    '''
    Function for parameters calculation of linear regression using least squares method
    x, y - numpy array objects
    '''
    
    # define experiment matrix
    X = np.ones((np.shape(x)[0], np.shape(x)[1] + 1))
    
    for i in range(0, np.shape(X)[0]):
        for j in range(1, np.shape(X)[1]):
            X[i][j] = x[i][j-1]
    print('Experiment matrix: \n'  + str(X))
    
    Xt = transpose(X)
    print('Transposition of X:\n' +str (Xt))
    
    XtX = multiplication(Xt, X)
    print('Multiplication of X transposed and X :\n' + str(XtX))
    
    XtX_inverse = inv(XtX)
    print('Inversion of X^t * X:\n' + str(XtX_inverse))
    
    Xty = multiplication(Xt, y)
    print('Multiplication of X^t and y:\n' + str(Xty))
    
    result = multiplication(XtX_inverse, Xty)
    print('Parameters:\n' + str(result))
    return(result)   

Wprowadzamy dane

In [5]:
x = np.array([[0.35],
              [0.45],
              [0.6],
              [0.95],
              [1.2],
              [1.7]])

y = np.array([[0.1],
              [0.15],
              [0.18],
              [0.24],
              [0.28],
              [0.35]])

Wyniki:

In [8]:
LSM_parameters(x, y)

Experiment matrix: 
[[1.   0.35]
 [1.   0.45]
 [1.   0.6 ]
 [1.   0.95]
 [1.   1.2 ]
 [1.   1.7 ]]
Transposition of X:
[[1.   1.   1.   1.   1.   1.  ]
 [0.35 0.45 0.6  0.95 1.2  1.7 ]]
Multiplication of X transposed and X :
[[6.     5.25  ]
 [5.25   5.9175]]
Inversion of X^t * X:
[[ 0.74504249 -0.66100094]
 [-0.66100094  0.75542965]]
Multiplication of X^t and y:
[[1.3   ]
 [1.3695]]
Parameters:
[[0.06331445]
 [0.17525968]]


array([[0.06331445],
       [0.17525968]])

Jako parametr $a_1 = 0.06331445$, $a_2 = 0.17525968$.