# Program 6

Aleksandra Burczyk \
Monika Gmaj \
Kinga Jankowska \
Kamil Łangowski

### Zadanie 1

Importujemy potrzebne biblioteki.

In [1]:
import pandas as pd
import numpy as np 
import scipy as sp
import sympy as sym

### Zadanie 2

Wczytujemy dane. 

In [2]:
churn = pd.read_csv("churn.txt")

In [3]:
churn

State  Account Length  Area Code     Phone Int'l Plan VMail Plan  \
0       KS             128        415  382-4657         no        yes   
1       OH             107        415  371-7191         no        yes   
2       NJ             137        415  358-1921         no         no   
3       OH              84        408  375-9999        yes         no   
4       OK              75        415  330-6626        yes         no   
...    ...             ...        ...       ...        ...        ...   
3328    AZ             192        415  414-4276         no        yes   
3329    WV              68        415  370-3271         no         no   
3330    RI              28        510  328-8230         no         no   
3331    CT             184        510  364-6381        yes         no   
3332    TN              74        415  400-4344         no        yes   

      VMail Message  Day Mins  Day Calls  Day Charge  ...  Eve Calls  \
0                25     265.1        110       45.07  ...         99   
1                26     161.6        123       27.47  ...        103   
2                 0     243.4        114       41.38  ...        110   
3                 0     299.4         71       50.90  ...         88   
4                 0     166.7        113       28.34  ...        122   
...             ...       ...        ...         ...  ...        ...   
3328             36     156.2         77       26.55  ...        126   
3329              0     231.1         57       39.29  ...         55   
3330              0     180.8        109       30.74  ...         58   
3331              0     213.8        105       36.35  ...         84   
3332             25     234.4        113       39.85  ...         82   

      Eve Charge  Night Mins  Night Calls  Night Charge  Intl Mins  \
0          16.78       244.7           91         11.01       10.0   
1          16.62       254.4          103         11.45       13.7   
2          10.30       162.6          104          7.32       12.2   
3           5.26       196.9           89          8.86        6.6   
4          12.61       186.9          121          8.41       10.1   
...          ...         ...          ...           ...        ...   
3328       18.32       279.1           83         12.56        9.9   
3329       13.04       191.3          123          8.61        9.6   
3330       24.55       191.9           91          8.64       14.1   
3331       13.57       139.2          137          6.26        5.0   
3332       22.60       241.4           77         10.86       13.7   

      Intl Calls  Intl Charge  CustServ Calls  Churn?  
0              3         2.70               1  False.  
1              3         3.70               1  False.  
2              5         3.29               0  False.  
3              7         1.78               2  False.  
4              3         2.73               3  False.  
...          ...          ...             ...     ...  
3328           6         2.67               2  False.  
3329           4         2.59               3  False.  
3330           6         3.81               2  False.  
3331          10         1.35               2  False.  
3332           4         3.70               0  False.  

[3333 rows x 21 columns]

### Zadanie 3

Usuwamy kropki z rekordów kolumny 'Churn?' przy pomocy funkcji ***replace***.

In [4]:
new_churn = churn['Churn?'].astype('str').str.replace(r".", r"", regex=False)

In [5]:
new_churn

0       False
1       False
2       False
3       False
4       False
        ...  
3328    False
3329    False
3330    False
3331    False
3332    False
Name: Churn?, Length: 3333, dtype: object

### Zadanie 4

Tworzymy nową ramkę danych wykorzystując funkcję ***copy()***. Ramka ta zawiera zmienne: 'Churn?' oraz 'Cust Serv Calls'.

In [6]:
churn['Churn?'] = new_churn

In [7]:
churn

State  Account Length  Area Code     Phone Int'l Plan VMail Plan  \
0       KS             128        415  382-4657         no        yes   
1       OH             107        415  371-7191         no        yes   
2       NJ             137        415  358-1921         no         no   
3       OH              84        408  375-9999        yes         no   
4       OK              75        415  330-6626        yes         no   
...    ...             ...        ...       ...        ...        ...   
3328    AZ             192        415  414-4276         no        yes   
3329    WV              68        415  370-3271         no         no   
3330    RI              28        510  328-8230         no         no   
3331    CT             184        510  364-6381        yes         no   
3332    TN              74        415  400-4344         no        yes   

      VMail Message  Day Mins  Day Calls  Day Charge  ...  Eve Calls  \
0                25     265.1        110       45.07  ...         99   
1                26     161.6        123       27.47  ...        103   
2                 0     243.4        114       41.38  ...        110   
3                 0     299.4         71       50.90  ...         88   
4                 0     166.7        113       28.34  ...        122   
...             ...       ...        ...         ...  ...        ...   
3328             36     156.2         77       26.55  ...        126   
3329              0     231.1         57       39.29  ...         55   
3330              0     180.8        109       30.74  ...         58   
3331              0     213.8        105       36.35  ...         84   
3332             25     234.4        113       39.85  ...         82   

      Eve Charge  Night Mins  Night Calls  Night Charge  Intl Mins  \
0          16.78       244.7           91         11.01       10.0   
1          16.62       254.4          103         11.45       13.7   
2          10.30       162.6          104          7.32       12.2   
3           5.26       196.9           89          8.86        6.6   
4          12.61       186.9          121          8.41       10.1   
...          ...         ...          ...           ...        ...   
3328       18.32       279.1           83         12.56        9.9   
3329       13.04       191.3          123          8.61        9.6   
3330       24.55       191.9           91          8.64       14.1   
3331       13.57       139.2          137          6.26        5.0   
3332       22.60       241.4           77         10.86       13.7   

      Intl Calls  Intl Charge  CustServ Calls  Churn?  
0              3         2.70               1   False  
1              3         3.70               1   False  
2              5         3.29               0   False  
3              7         1.78               2   False  
4              3         2.73               3   False  
...          ...          ...             ...     ...  
3328           6         2.67               2   False  
3329           4         2.59               3   False  
3330           6         3.81               2   False  
3331          10         1.35               2   False  
3332           4         3.70               0   False  

[3333 rows x 21 columns]

In [8]:
new_df = churn[['Churn?','CustServ Calls']].copy()

In [52]:
new_df.head(15)

Churn?      CSC
0   False     małe
1   False     małe
2   False     małe
3   False  średnie
4   False  średnie
5   False     małe
6   False  średnie
7   False     małe
8   False     małe
9   False     małe
10   True  wysokie
11  False     małe
12  False     małe
13  False  średnie
14  False  wysokie

### Zadanie 5

Tworzymy nową zmienną bazując na poniższych warunkach:
- 0 lub 1 rozmowa z biurem obsługi klienta $\Longleftrightarrow$ CSC przyjmuje wartości małe
- 2 lub 3 rozmowy z biurem obsługi klienta $\Longleftrightarrow$ CSC przyjmuje wartości średnie
- 4 lub więcej rozmów z biurem obsługi klienta $\Longleftrightarrow$ CSC przyjmuje wartości wysokie

W tym celu korzystamy z funkcji ***where*** z pakietu **numpy**. Zwraca ona elementy na podstawie postawionych warunków. 

In [10]:
new_df['CustServ Calls'] = np.where((new_df['CustServ Calls'] >= 0) & (new_df['CustServ Calls'] <= 1), 'małe',
                   np.where((new_df['CustServ Calls'] >= 2) & (new_df['CustServ Calls'] <= 3), 'średnie', 'wysokie'))

In [51]:
new_df.rename({'CustServ Calls': 'CSC'}, axis=1, inplace=True)
new_df
new_df.head(15)

Churn?      CSC
0   False     małe
1   False     małe
2   False     małe
3   False  średnie
4   False  średnie
5   False     małe
6   False  średnie
7   False     małe
8   False     małe
9   False     małe
10   True  wysokie
11  False     małe
12  False     małe
13  False  średnie
14  False  wysokie

### Zadanie 6

Tworzymy tabelę krzyżową zmiennych 'Churn?' oraz 'CustServ Calls'. Korzystamy z funkcji ***crosstable*** pochodzącej z pakietu **pandas**. 

In [12]:
tabela = pd.crosstab(new_df['Churn?'], new_df['CSC'])

In [13]:
tabela

CSC     małe  wysokie  średnie
Churn?                        
False   1664      129     1057
True     214      138      131

In [14]:
tab = tabela[['małe','średnie','wysokie']].copy()

In [15]:
tab

CSC     małe  średnie  wysokie
Churn?                        
False   1664     1057      129
True     214      131      138

### Zadanie 7

Tworzymy dwie nowe zmienne wskaźnikowe o nazwach 'CSC_sr' i 'CSC_wys':
- dla małej liczby rozmów CSC_sr = 0, CSC_wys = 0
- dla średniej liczby rozmów CSC_sr = 1, CSC_wys = 0
- dla wysokiej liczby rozmów CSC_sr = 0, CSC_wys = 1

In [16]:
conditions = [new_df['CSC'] == "małe",  new_df['CSC'] == "średnie", new_df['CSC'] == "wysokie"]
choices_sr = [0,1,0]
choices_wys = [0,0,1]

In [17]:
CSC_sr = np.select(conditions, choices_sr)

In [18]:
CSC_sr

array([0, 0, 0, ..., 1, 1, 0])

In [55]:
CSC_sr[0:15]

array([0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0])

In [19]:
CSC_wys = np.select(conditions, choices_wys)

In [48]:
CSC_wys

array([0, 0, 0, ..., 0, 0, 0])

In [56]:
CSC_wys[0:15]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1])

### Zadanie 8 

Wykorzystując tabelę krzyżową powstałą przy zadaniu 6 wyznaczymy ilorazy szans OR_nis, OR_śr, OR_wys.

In [21]:
tab

CSC     małe  średnie  wysokie
Churn?                        
False   1664     1057      129
True     214      131      138

In [61]:
a = tab.iloc[0,0]

In [62]:
b = tab.iloc[0,1]

In [63]:
c = tab.iloc[0,2]

In [64]:
d = tab.iloc[1,0]

In [65]:
e = tab.iloc[1,1]

In [66]:
f = tab.iloc[1,2]

Mała wartość jako kategoria odniesienia. 

In [67]:
OR_nis = d/a

In [68]:
OR_śr = (a*e)/(b*d)

In [69]:
OR_wys = (a*f)/(c*d)

In [70]:
print(' OR_nis =',OR_nis,'\n OR_śr =',OR_śr,'\n OR_wys =',OR_wys)

 OR_nis = 0.12860576923076922 
 OR_śr = 0.9636866815798548 
 OR_wys = 8.318191697457074


### Zadanie 9

Obliczymy współczynniki $b_0, b_1, b_2$, gdzie 
* $b_0$ to logarytm naturalny z ilorazu szans OR_nis
* $b_1$ to logarytm naturalny z ilorazu szans OR_śr
* $b_2$ to logarytm naturalny z ilorazu szans OR_wys

Na początku  $b_0, b_1, b_2$ dla ilorazów szans dla niskiej wartości jako kategorii odniesienia.

In [71]:
b0 = np.log(OR_nis)

In [72]:
b1 = np.log(OR_śr)

In [73]:
b2 = np.log(OR_wys)

In [74]:
print(' b0 =',b0,'\n b1 =',b1,'\n b2 =',b2)

 b0 = -2.0510036063593025 
 b1 = -0.03698905630978367 
 b2 = 2.118444887154835


### Zadanie 10 

Zapiszemy funkcje logitowe $g(X = [x,y]) = b_0 + b_1 x + b_2 y$, dla wyznaczonych wyżej wartości współczynników $b_0, b_1, b_2$. 


Najpierw zapisujemy $x, y$ jako symbole wykorzystując przy tym pakiet **sympy**. 

In [75]:
x = sym.Symbol('x')
y = sym.Symbol('y')

In [76]:
g_n = b0 + b1*x + b2*y
print('g([x,y]) = ',g_n)

g([x,y]) =  -0.0369890563097837*x + 2.11844488715484*y - 2.0510036063593


### Zadanie 11

Zapisz prawdopodobieństwo przeniesienia się
$\Pi (X) = \frac{e^{g(X)}}{1+e^{g(X)}} $

Prawdopodobieństwo przeniesienia dla niskiej wartości jako kat. odniesienia. 

In [77]:
((sym.exp(g_n))/(1+sym.exp(g_n))).evalf()

0.128605769230769*exp(-0.0369890563097837*x + 2.11844488715484*y)/(0.128605769230769*exp(-0.0369890563097837*x + 2.11844488715484*y) + 1.0)

### Zadanie 12

Obliczamy prawdopodobieństwa przeniesienia się w zależności od tego, czy klient odbył mało/średnio/dużo rozmów z biurem obsługi klienta. Wykorzystujemy w tym celu naszą tabelę krzyżową. 

In [78]:
P_n = d/(a+d)

In [79]:
P_ś = e/(b+e)

In [80]:
P_w = f/(c+f)

In [81]:
print(' P_n =',P_n,'\n P_ś =',P_ś,'\n P_w =',P_w)

 P_n = 0.11395101171458999 
 P_ś = 0.11026936026936027 
 P_w = 0.5168539325842697


### Zadanie 13

Obliczamy dodatkowo prawdopodobieństwo przeniesienia się bez podziału na liczbę rozmów.

In [45]:
P = (d+e+f)/(a+b+c+d+e+f)

In [46]:
print('P =',P)

P = 0.14491449144914492


### Zadanie 14

Wnioski: Prawdopodobieństwo, że klient się przeniesie wykonując dużo telefonów do BOK wynosi ponad 50%. Prawdopodobieństwo, że się przeniesie wykonując mało/średnio telefonów do BOK jest zbliżone do prawdopodobieństwa przeniesienia się bez podziału na liczbę telefonów do BOK, wszystkie te trzy prawdopodobieństwa należą do przedziału 11-15%. Dlatego też firma jest najbardziej narażona na stratę klientów, którzy wykonali dużo telefonów do BOK. 